CCC = g++
LEX = flex
YACC = bison
CFLAGS = -Wall -std=c++11
LEXFLAGS = -Wno-unused

#LEXDEBUG = -d
LEXDEBUG =
YACCDEBUG = -vtd

OBJS = main.o ast.o parse.tab.o lex.yy.o SymbolTable.o

run: $(OBJS)
	$(CCC) $(CFLAGS) -o run $(OBJS)

main.o: main.cpp parse.y scan.l parse.tab.cpp lex.yy.cpp 
	$(CCC) $(CFLAGS) -c main.cpp

ast.o:  ast.cpp   ast.h 
	$(CCC) $(CFLAGS) -c   ast.cpp
	
parse.tab.cpp:   parse.y   ast.h
	$(YACC) -o parse.tab.cpp $(YACCDEBUG)   parse.y

parse.tab.o: parse.tab.cpp
	$(CCC) $(CFLAGS) -c parse.tab.cpp

lex.yy.cpp:   scan.l parse.tab.o
	$(LEX) -o lex.yy.cpp $(LEXDEBUG)   scan.l

lex.yy.o: lex.yy.cpp
	$(CCC) $(CFLAGS) $(LEXFLAGS) -c lex.yy.cpp
	
SymbolTable.o: SymbolTable.cpp SymbolTable.h
	$(CCC) $(CFLAGS) -c   SymbolTable.cpp
clean:
	rm -f run *.o   *.o parse.tab.cpp lex.yy.cpp
	rm -f parse.tab.hpp
	rm -f parse.output
